import Head from 'next/head'
import GlobalNavbar from '../components/common/GlobalNavbar/GlobalNavbar'
import HeroSection from '../components/Home/HeroSection/HeroSection'
import WorkStrategy from '../components/Home/WorkStrategy/WorkStrategy'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GlobalNavbar />
      <HeroSection/>
      <WorkStrategy/>
    </div>
  )
}
